// Generated by Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CometChatSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum messageType : NSInteger;
enum receiverType : NSInteger;
enum MessageCategory : NSInteger;
@class User;

SWIFT_CLASS("_TtC12CometChatSDK11BaseMessage")
@interface BaseMessage : NSObject
@property (nonatomic) NSUInteger id;
@property (nonatomic, copy) NSString * _Nonnull muid;
@property (nonatomic, copy) NSString * _Nonnull senderUid;
@property (nonatomic, copy) NSString * _Nonnull receiverUid;
@property (nonatomic) enum messageType messageType;
@property (nonatomic) enum receiverType receiverType;
@property (nonatomic) double sentAt;
@property (nonatomic, copy) NSString * _Nonnull status;
@property (nonatomic) enum MessageCategory messageCategory;
@property (nonatomic, strong) User * _Nullable sender;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (nonnull instancetype)initWithReceiverUid:(NSString * _Nonnull)receiverUid messageType:(enum messageType)messageType receiverType:(enum receiverType)receiverType OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12CometChatSDK13ActionMessage")
@interface ActionMessage : BaseMessage
- (nonnull instancetype)initWithReceiverUid:(NSString * _Nonnull)receiverUid messageType:(enum messageType)messageType receiverType:(enum receiverType)receiverType OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12CometChatSDK9AppEntity")
@interface AppEntity : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP12CometChatSDK11CustomError_")
@protocol CustomError
@property (nonatomic, readonly, copy) NSString * _Nonnull errordescription;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorcode;
@end


SWIFT_CLASS("_TtC12CometChatSDK11CCException")
@interface CCException : NSObject <CustomError>
@property (nonatomic, copy) NSString * _Nonnull errordescription;
@property (nonatomic, copy) NSString * _Nonnull errorcode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

enum callStatus : NSInteger;

SWIFT_CLASS("_TtC12CometChatSDK4Call")
@interface Call : BaseMessage
@property (nonatomic, copy) NSString * _Nullable sessionID;
@property (nonatomic) enum callStatus callStatus;
@property (nonatomic, copy) NSString * _Nullable metaData;
@property (nonatomic, copy) NSString * _Nullable action;
@property (nonatomic, copy) NSString * _Nullable rawData;
@property (nonatomic) double initiatedAt;
- (nonnull instancetype)initWithReceiverId:(NSString * _Nonnull)receiverId messageType:(enum messageType)messageType receiverType:(enum receiverType)receiverType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithReceiverUid:(NSString * _Nonnull)receiverUid messageType:(enum messageType)messageType receiverType:(enum receiverType)receiverType SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC12CometChatSDK9CometChat")
@interface CometChat : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (nonnull instancetype)initWithAppId:(NSString * _Nonnull)appId onError:(void (^ _Nonnull)(CCException * _Nonnull))onError OBJC_DESIGNATED_INITIALIZER;
+ (void)KickAMemberWithUid:(NSString * _Nonnull)uid guid:(NSString * _Nonnull)guid onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)getUserWithUid:(NSString * _Nonnull)WithUid completionHandler:(void (^ _Nonnull)(User * _Nullable, CCException * _Nullable))completionHandler;
+ (void)getMyDetailsOnSuccess:(void (^ _Nonnull)(User * _Nullable))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)getPreviousMessagesByTimestampWithLimit:(NSInteger)limit timeStamp:(NSInteger)timeStamp onSuccess:(void (^ _Nonnull)(NSArray<BaseMessage *> * _Nullable))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)getPreviousMessagesByIdWithLimit:(NSInteger)limit messageId:(NSInteger)messageId onSuccess:(void (^ _Nonnull)(NSArray<BaseMessage *> * _Nullable))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)getNextMessagesByTimestampWithLimit:(NSInteger)limit timeStamp:(NSInteger)timeStamp onSuccess:(void (^ _Nonnull)(NSArray<BaseMessage *> * _Nullable))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)getNextMessagesByIdWithLimit:(NSInteger)limit messageId:(NSInteger)messageId onSuccess:(void (^ _Nonnull)(NSArray<BaseMessage *> * _Nullable))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)getAllMessagesWithLimit:(NSInteger)limit timestamp:(NSInteger)timestamp id:(NSInteger)id affix:(NSString * _Nonnull)affix page:(NSInteger)page onSuccess:(void (^ _Nonnull)(NSArray<BaseMessage *> * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)banUserForGuid:(NSString * _Nonnull)ForGuid Withuid:(NSString * _Nonnull)Withuid onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)getBannedUsersListForAgroupWithGuid:(NSString * _Nonnull)guid success:(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))success onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)unBanUserForGuid:(NSString * _Nonnull)ForGuid WithUid:(NSString * _Nonnull)WithUid success:(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))success onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
@end

@class TextMessage;
@class MediaMessage;

@interface CometChat (SWIFT_EXTENSION(CometChatSDK))
+ (void)sendTextMessageWithMessage:(TextMessage * _Nonnull)message onSuccess:(void (^ _Nonnull)(BaseMessage * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)sendMediaMessageWithMessage:(MediaMessage * _Nonnull)message onSuccess:(void (^ _Nonnull)(BaseMessage * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
@end


@interface CometChat (SWIFT_EXTENSION(CometChatSDK))
+ (void)loginWithUid:(NSString * _Nonnull)withUid apiKey:(NSString * _Nonnull)apiKey onSuccess:(void (^ _Nonnull)(User * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)loginWithAuthToken:(NSString * _Nonnull)withAuthToken onSuccess:(void (^ _Nonnull)(User * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
@end

@class Group;
enum groupType : NSInteger;

@interface CometChat (SWIFT_EXTENSION(CometChatSDK))
+ (void)createGroupWithGroup:(Group * _Nonnull)group onSuccess:(void (^ _Nonnull)(Group * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)joinGroupWithGuid:(NSString * _Nonnull)guid groupType:(enum groupType)groupType password:(NSString * _Nullable)password onSuccess:(void (^ _Nonnull)(Group * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)getGroupWithGuid:(NSString * _Nonnull)WithGuid completionHandler:(void (^ _Nonnull)(Group * _Nullable, CCException * _Nullable))completionHandler;
+ (void)leaveGroupWithGuid:(NSString * _Nonnull)guid onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
@end

@class UIView;

@interface CometChat (SWIFT_EXTENSION(CometChatSDK))
+ (void)sendCallRequestWithCall:(Call * _Nonnull)call onSuccess:(void (^ _Nonnull)(Call * _Nullable))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)acceptCallWithCall:(Call * _Nonnull)call onSuccess:(void (^ _Nonnull)(Call * _Nullable))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)rejectCallWithCall:(Call * _Nonnull)call status:(enum callStatus)status onSuccess:(void (^ _Nonnull)(Call * _Nullable))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)endCallWithCall:(Call * _Nonnull)call status:(enum callStatus)status onSuccess:(void (^ _Nonnull)(Call * _Nullable))onSuccess onFailure:(void (^ _Nonnull)(CCException * _Nullable))onFailure;
+ (void)startCallWithCall:(Call * _Nonnull)call inView:(UIView * _Nonnull)inView userJoined:(void (^ _Nonnull)(User * _Nullable))userJoined userLeft:(void (^ _Nonnull)(User * _Nullable))userLeft error:(void (^ _Nonnull)(CCException * _Nullable))error callEnded:(void (^ _Nonnull)(Call * _Nullable))callEnded;
@end


@interface CometChat (SWIFT_EXTENSION(CometChatSDK))
+ (void)startServices;
+ (void)stopServices;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isCallOngoing;)
+ (BOOL)isCallOngoing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Call * _Nullable currentCall;)
+ (Call * _Nullable)currentCall SWIFT_WARN_UNUSED_RESULT;
@end

@protocol CometChatMessageDelegate;
@protocol CometChatCallDelegate;
@protocol CometChatUserEventDelegate;
@protocol CometChatGroupEventDelegate;

@interface CometChat (SWIFT_EXTENSION(CometChatSDK))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, weak) id <CometChatMessageDelegate> _Nullable messagedelegate;)
+ (id <CometChatMessageDelegate> _Nullable)messagedelegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setMessagedelegate:(id <CometChatMessageDelegate> _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, weak) id <CometChatCallDelegate> _Nullable calldelegate;)
+ (id <CometChatCallDelegate> _Nullable)calldelegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setCalldelegate:(id <CometChatCallDelegate> _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, weak) id <CometChatUserEventDelegate> _Nullable userEventdelegate;)
+ (id <CometChatUserEventDelegate> _Nullable)userEventdelegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserEventdelegate:(id <CometChatUserEventDelegate> _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, weak) id <CometChatGroupEventDelegate> _Nullable groupEventdelegate;)
+ (id <CometChatGroupEventDelegate> _Nullable)groupEventdelegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setGroupEventdelegate:(id <CometChatGroupEventDelegate> _Nullable)value;
@end


SWIFT_PROTOCOL("_TtP12CometChatSDK21CometChatCallDelegate_")
@protocol CometChatCallDelegate
- (void)onIncomingCallWithAIncomingCall:(Call * _Nullable)aIncomingCall error:(CCException * _Nullable)error;
- (void)onCallAcceptedWithAAcceptedCall:(Call * _Nullable)aAcceptedCall error:(CCException * _Nullable)error;
- (void)onCallRejectedWithARejectedCall:(Call * _Nullable)aRejectedCall error:(CCException * _Nullable)error;
@end


SWIFT_CLASS("_TtC12CometChatSDK18CometChatConstants")
@interface CometChatConstants : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, affix, closed) {
  affixPrepend = 0,
  affixAppend = 1,
};

typedef SWIFT_ENUM(NSInteger, MessageCategory, closed) {
  MessageCategoryMessage = 0,
  MessageCategoryAction = 1,
  MessageCategoryCall = 2,
};

typedef SWIFT_ENUM(NSInteger, receiverType, closed) {
  receiverTypeUser = 0,
  receiverTypeGroup = 1,
};

typedef SWIFT_ENUM(NSInteger, messageType, closed) {
  messageTypeText = 0,
  messageTypeImage = 1,
  messageTypeVideo = 2,
  messageTypeAudio = 3,
  messageTypeFile = 4,
  messageTypeHandwrite = 5,
  messageTypeGroupMember = 6,
};

typedef SWIFT_ENUM(NSInteger, actionType, closed) {
  actionTypeJoined = 0,
  actionTypeLeft = 1,
  actionTypeKicked = 2,
  actionTypeOutcasted = 3,
  actionTypeReinstated = 4,
  actionTypeInvited = 5,
  actionTypeScopeChanged = 6,
};

typedef SWIFT_ENUM(NSInteger, groupType, closed) {
  groupTypePublic = 0,
  groupTypePrivate = 1,
  groupTypeProtected = 2,
};

typedef SWIFT_ENUM(NSInteger, callStatus, closed) {
  callStatusInitiated = 0,
  callStatusOngoing = 1,
  callStatusUnanswered = 2,
  callStatusRejected = 3,
  callStatusBusy = 4,
  callStatusCanceled = 5,
  callStatusEnded = 6,
};


SWIFT_PROTOCOL("_TtP12CometChatSDK27CometChatGroupEventDelegate_")
@protocol CometChatGroupEventDelegate
- (void)onUserJoinedWithJoinedUser:(User * _Nonnull)joinedUser joinedGroup:(Group * _Nonnull)joinedGroup;
- (void)onUserLeftWithLeftUser:(User * _Nonnull)leftUser leftGroup:(Group * _Nonnull)leftGroup;
- (void)onUserKickedWithKickedUser:(User * _Nonnull)kickedUser kickedBy:(User * _Nonnull)kickedBy kickedFrom:(Group * _Nonnull)kickedFrom;
- (void)onUserBannedWithBannedUser:(User * _Nonnull)bannedUser bannedBy:(User * _Nonnull)bannedBy bannedFrom:(Group * _Nonnull)bannedFrom;
- (void)onUserUnbannedWithUnbannedUser:(User * _Nonnull)unbannedUser unbannedBy:(User * _Nonnull)unbannedBy unbannedFrom:(Group * _Nonnull)unbannedFrom;
- (void)onMemberScopeChangedWithUser:(User * _Nonnull)user scopeChangedTo:(NSString * _Nonnull)scopeChangedTo scopeChangedFrom:(NSString * _Nonnull)scopeChangedFrom group:(Group * _Nonnull)group;
@end


SWIFT_PROTOCOL("_TtP12CometChatSDK24CometChatMessageDelegate_")
@protocol CometChatMessageDelegate
- (void)onTextMessageReceivedWithATextMessage:(TextMessage * _Nullable)aTextMessage error:(CCException * _Nullable)error;
- (void)onMediaMessageReceivedWithAMediaMessage:(MediaMessage * _Nullable)aMediaMessage error:(CCException * _Nullable)error;
- (void)onActionMessageReceivedWithAActionMessage:(ActionMessage * _Nullable)aActionMessage error:(CCException * _Nullable)error;
@end


SWIFT_PROTOCOL("_TtP12CometChatSDK26CometChatUserEventDelegate_")
@protocol CometChatUserEventDelegate
- (void)onUserOnlineWithUser:(User * _Nonnull)user;
- (void)onUserOfflineWithUser:(User * _Nonnull)user;
@end


SWIFT_CLASS("_TtC12CometChatSDK4User")
@interface User : AppEntity
@property (nonatomic, copy) NSString * _Nonnull uid;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable link;
@property (nonatomic, copy) NSString * _Nullable role;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
@property (nonatomic) NSInteger credits;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusMessage;
@property (nonatomic) double lastActiveAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUid:(NSString * _Nonnull)uid name:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUid:(NSString * _Nonnull)uid name:(NSString * _Nonnull)name email:(NSString * _Nonnull)email avatar:(NSString * _Nonnull)avatar link:(NSString * _Nonnull)link role:(NSString * _Nonnull)role metadata:(NSDictionary<NSString *, NSString *> * _Nonnull)metadata credits:(NSInteger)credits status:(NSString * _Nonnull)status statusMessage:(NSString * _Nonnull)statusMessage lastActiveAt:(double)lastActiveAt OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12CometChatSDK11CurrentUser")
@interface CurrentUser : User
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUid:(NSString * _Nonnull)uid name:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUid:(NSString * _Nonnull)uid name:(NSString * _Nonnull)name email:(NSString * _Nonnull)email avatar:(NSString * _Nonnull)avatar link:(NSString * _Nonnull)link role:(NSString * _Nonnull)role metadata:(NSDictionary<NSString *, NSString *> * _Nonnull)metadata credits:(NSInteger)credits status:(NSString * _Nonnull)status statusMessage:(NSString * _Nonnull)statusMessage lastActiveAt:(double)lastActiveAt OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC12CometChatSDK5Group")
@interface Group : AppEntity
@property (nonatomic, copy) NSString * _Nullable guid;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable icon;
@property (nonatomic, copy) NSString * _Nullable groupDescription;
@property (nonatomic, copy) NSString * _Nullable owner;
@property (nonatomic, copy) NSString * _Nullable groupType;
@property (nonatomic, copy) NSString * _Nullable password;
@property (nonatomic, copy) NSString * _Nullable metadata;
@property (nonatomic) NSInteger createdAt;
@property (nonatomic) NSInteger updatedAt;
@property (nonatomic) BOOL isJoined;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (nonnull instancetype)initWithGuid:(NSString * _Nonnull)guid name:(NSString * _Nonnull)name groupType:(enum groupType)groupType password:(NSString * _Nullable)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithGuid:(NSString * _Nonnull)guid name:(NSString * _Nonnull)name groupType:(enum groupType)groupType password:(NSString * _Nullable)password icon:(NSString * _Nonnull)icon description:(NSString * _Nonnull)description OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12CometChatSDK11GroupMember")
@interface GroupMember : NSObject
@property (nonatomic, copy) NSString * _Nullable guid;
@property (nonatomic, copy) NSString * _Nullable uid;
@property (nonatomic, copy) NSString * _Nullable scope;
@property (nonatomic, strong) User * _Nullable user;
@property (nonatomic) NSInteger joinedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class GroupMembersRequestBuilder;

SWIFT_CLASS("_TtC12CometChatSDK19GroupMembersRequest")
@interface GroupMembersRequest : NSObject
- (nonnull instancetype)initWithBuilder:(GroupMembersRequestBuilder * _Nonnull)builder OBJC_DESIGNATED_INITIALIZER;
- (void)fetchNextWithCompletionHandler:(void (^ _Nonnull)(NSArray<GroupMember *> * _Nullable, CCException * _Nullable))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC12CometChatSDK19GroupMembersRequest26GroupMembersRequestBuilder")
@interface GroupMembersRequestBuilder : NSObject
- (nonnull instancetype)initWithGuid:(NSString * _Nonnull)guid OBJC_DESIGNATED_INITIALIZER;
- (GroupMembersRequestBuilder * _Nonnull)setLimitWithLimit:(NSInteger)limit SWIFT_WARN_UNUSED_RESULT;
- (GroupMembersRequest * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class GroupMessagesRequestBuilder;

SWIFT_CLASS("_TtC12CometChatSDK20GroupMessagesRequest")
@interface GroupMessagesRequest : NSObject
- (nonnull instancetype)initWithBuilder:(GroupMessagesRequestBuilder * _Nonnull)builder OBJC_DESIGNATED_INITIALIZER;
- (void)fetchPreviousWithCompletionHandler:(void (^ _Nonnull)(NSArray<BaseMessage *> * _Nullable, CCException * _Nullable))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC12CometChatSDK20GroupMessagesRequest27GroupMessagesRequestBuilder")
@interface GroupMessagesRequestBuilder : NSObject
- (nonnull instancetype)initWithGuid:(NSString * _Nonnull)guid OBJC_DESIGNATED_INITIALIZER;
- (GroupMessagesRequestBuilder * _Nonnull)setLimitWithLimit:(NSInteger)limit SWIFT_WARN_UNUSED_RESULT;
- (GroupMessagesRequest * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class GroupsRequestBuilder;

SWIFT_CLASS("_TtC12CometChatSDK13GroupsRequest")
@interface GroupsRequest : NSObject
- (nonnull instancetype)initWithBuilder:(GroupsRequestBuilder * _Nonnull)builder OBJC_DESIGNATED_INITIALIZER;
- (void)fetchNextWithCompletionHandler:(void (^ _Nonnull)(NSArray<Group *> * _Nullable, CCException * _Nullable))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC12CometChatSDK13GroupsRequest20GroupsRequestBuilder")
@interface GroupsRequestBuilder : NSObject
- (nonnull instancetype)initWithLimit:(NSInteger)Limit OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSearchKeyword:(NSString * _Nonnull)SearchKeyword OBJC_DESIGNATED_INITIALIZER;
- (GroupsRequest * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12CometChatSDK12MediaMessage")
@interface MediaMessage : BaseMessage
/// send media message
/// \param receiverUid receiver’s uid
///
/// \param file Data of file to be sent
///
/// \param messageType message type
///
/// \param receiverType receiver type
///
- (nonnull instancetype)initWithReceiverUid:(NSString * _Nonnull)receiverUid fileurl:(NSURL * _Nonnull)fileurl messageType:(enum messageType)messageType receiverType:(enum receiverType)receiverType OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nonnull metaData;
@property (nonatomic, copy) NSURL * _Nullable url;
- (nonnull instancetype)initWithReceiverUid:(NSString * _Nonnull)receiverUid messageType:(enum messageType)messageType receiverType:(enum receiverType)receiverType SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC12CometChatSDK11TextMessage")
@interface TextMessage : BaseMessage
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic, copy) NSString * _Nullable metaData;
- (nonnull instancetype)initWithReceiverUid:(NSString * _Nonnull)receiverUid text:(NSString * _Nonnull)text messageType:(enum messageType)messageType receiverType:(enum receiverType)receiverType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithReceiverUid:(NSString * _Nonnull)receiverUid messageType:(enum messageType)messageType receiverType:(enum receiverType)receiverType SWIFT_UNAVAILABLE;
@end


@class UserMessagesRequestBuilder;

SWIFT_CLASS("_TtC12CometChatSDK19UserMessagesRequest")
@interface UserMessagesRequest : NSObject
- (nonnull instancetype)initWithBuilder:(UserMessagesRequestBuilder * _Nonnull)builder OBJC_DESIGNATED_INITIALIZER;
- (void)fetchPreviousWithCompletionHandler:(void (^ _Nonnull)(NSArray<BaseMessage *> * _Nullable, CCException * _Nullable))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC12CometChatSDK19UserMessagesRequest26UserMessagesRequestBuilder")
@interface UserMessagesRequestBuilder : NSObject
- (nonnull instancetype)initFromUID:(NSString * _Nonnull)fromUID OBJC_DESIGNATED_INITIALIZER;
- (UserMessagesRequestBuilder * _Nonnull)setLimitWithLimit:(NSInteger)limit SWIFT_WARN_UNUSED_RESULT;
- (UserMessagesRequest * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UsersRequestBuilder;

SWIFT_CLASS("_TtC12CometChatSDK12UsersRequest")
@interface UsersRequest : NSObject
- (nonnull instancetype)initWithBuilder:(UsersRequestBuilder * _Nonnull)builder OBJC_DESIGNATED_INITIALIZER;
- (void)fetchNextWithCompletionHandler:(void (^ _Nonnull)(NSArray<User *> * _Nullable, CCException * _Nullable))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC12CometChatSDK12UsersRequest19UsersRequestBuilder")
@interface UsersRequestBuilder : NSObject
- (nonnull instancetype)initWithSearchKeyword:(NSString * _Nonnull)searchKeyword OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLimit:(NSInteger)limit OBJC_DESIGNATED_INITIALIZER;
- (UsersRequest * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
